# Generated by Django 5.1 on 2024-08-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.URLField(max_length=1000, null=True)),
                ('contact_info', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='api_advisor_id_41fe24_idx')],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(max_length=1000, null=True)),
                ('profile_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='api_author_id_8494dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('df', 'Draft'), ('pb', 'Publish')], default='pb', max_length=5)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
            options={
                'ordering': ['reviews_count'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.URLField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('df', 'Draft'), ('pb', 'Publish')], default='pb', max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='api_blog_title_33ec30_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['reviews_count'], name='api_service_reviews_700d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-rating'], name='api_review_rating_9fbd3b_idx'),
        ),
    ]
