# Generated by Django 5.1 on 2024-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='image',
            field=models.URLField(max_length=9000, null=True),
        ),
    ]
